# Generated by Django 5.2.17 on 2026-08-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_image_alter_product_secondary_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='drape_ease',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Expert', 'Expert')], default='Easy', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='sheen',
            field=models.CharField(choices=[('Matte', 'Matte'), ('Subtle Luster', 'Subtle Luster'), ('High Luster', 'High Luster')], default='Matte', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='transparency',
            field=models.CharField(choices=[('Opaque', 'Opaque'), ('Semi-Sheer', 'Semi-Sheer'), ('Sheer', 'Sheer')], default='Opaque', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(default='Medium 400g', max_length=50),
        ),
    ]
