# Generated by Django 5.2.17 on 2026-08-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_drape_ease_product_sheen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flat_lay_image',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
