# Generated by Django 5.2.17 on 2026-08-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_ugcpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for no sale. Set a value to show discounted price.', max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='UGCPost',
        ),
    ]
